CREATE TABLE roles
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (name) VALUES('ADMIN');
INSERT INTO roles (name) VALUES('USER');