package model

// PrettyFitFile encapsulates a PrettyFit json file
type PrettyFitFile struct {
	FileID struct {
		SerialNumber int64  `json:"serial_number"`
		TimeCreated  int    `json:"time_created"`
		Manufacturer string `json:"manufacturer"`
		Product      string `json:"product"`
		Number       int    `json:"number"`
		Type         string `json:"type"`
	} `json:"file_id"`
	FileCreator struct {
		SoftwareVersion string `json:"software_version"`
		HardwareVersion string `json:"hardware_version"`
	} `json:"file_creator"`
	Events []struct {
		Timestamp    int    `json:"timestamp"`
		TimerTrigger string `json:"timer_trigger"`
		Event        string `json:"event"`
		EventType    string `json:"event_type"`
		EventGroup   int    `json:"event_group"`
	} `json:"events"`
	DeviceInfos []struct {
		Timestamp        int     `json:"timestamp"`
		SerialNumber     int64   `json:"serial_number"`
		CumOperatingTime int64   `json:"cum_operating_time"`
		Manufacturer     string  `json:"manufacturer"`
		Product          string  `json:"product"`
		SoftwareVersion  float64 `json:"software_version"`
		BatteryVoltage   float64 `json:"battery_voltage"`
		DeviceIndex      string  `json:"device_index"`
		DeviceType       int     `json:"device_type"`
		HardwareVersion  int     `json:"hardware_version"`
		BatteryStatus    int     `json:"battery_status"`
		SourceType       string  `json:"source_type"`
		AntNetwork       string  `json:"ant_network"`
	} `json:"device_infos"`
	DeviceSettings struct {
		UtcOffset                         int    `json:"utc_offset"`
		TimeOffset                        int    `json:"time_offset"`
		AutosyncMinSteps                  int    `json:"autosync_min_steps"`
		AutosyncMinTime                   int    `json:"autosync_min_time"`
		ActiveTimeZone                    int    `json:"active_time_zone"`
		TimeMode                          string `json:"time_mode"`
		TimeZoneOffset                    int    `json:"time_zone_offset"`
		BacklightMode                     string `json:"backlight_mode"`
		ActivityTrackerEnabled            bool   `json:"activity_tracker_enabled"`
		MoveAlertEnabled                  bool   `json:"move_alert_enabled"`
		MountingSide                      int    `json:"mounting_side"`
		LactateThresholdAutodetectEnabled bool   `json:"lactate_threshold_autodetect_enabled"`
		NumberOfScreens                   int    `json:"number_of_screens"`
	} `json:"device_settings"`
	UserProfile struct {
		LocaltimeIntoDay            float64 `json:"localtime_into_day"`
		LocaltimeIntoDayOffset      float64 `json:"localtime_into_day_offset"`
		LocaltimeIntoDayScale       float64 `json:"localtime_into_day_scale"`
		LocaltimeIntoDayUnit        string  `json:"localtime_into_day_unit"`
		SleepTime                   float64 `json:"sleep_time"`
		SleepTimeOffset             float64 `json:"sleep_time_offset"`
		SleepTimeScale              float64 `json:"sleep_time_scale"`
		SleepTimeUnit               string  `json:"sleep_time_unit"`
		Weight                      float64 `json:"weight"`
		WeightOffset                float64 `json:"weight_offset"`
		WeightScale                 float64 `json:"weight_scale"`
		WeightUnit                  string  `json:"weight_unit"`
		UserRunningStepLength       float64 `json:"user_running_step_length"`
		UserRunningStepLengthOffset float64 `json:"user_running_step_length_offset"`
		UserRunningStepLengthScale  float64 `json:"user_running_step_length_scale"`
		UserRunningStepLengthUnit   string  `json:"user_running_step_length_unit"`
		UserWalkingStepLength       float64 `json:"user_walking_step_length"`
		UserWalkingStepLengthOffset float64 `json:"user_walking_step_length_offset"`
		UserWalkingStepLengthScale  float64 `json:"user_walking_step_length_scale"`
		UserWalkingStepLengthUnit   string  `json:"user_walking_step_length_unit"`
		Gender                      string  `json:"gender"`
		Height                      float64 `json:"height"`
		HeightOffset                float64 `json:"height_offset"`
		HeightScale                 float64 `json:"height_scale"`
		HeightUnit                  string  `json:"height_unit"`
		Language                    string  `json:"language"`
		ElevSetting                 string  `json:"elev_setting"`
		WeightSetting               string  `json:"weight_setting"`
		RestingHeartRate            float64 `json:"resting_heart_rate"`
		RestingHeartRateOffset      float64 `json:"resting_heart_rate_offset"`
		RestingHeartRateScale       float64 `json:"resting_heart_rate_scale"`
		RestingHeartRateUnit        string  `json:"resting_heart_rate_unit"`
		HrSetting                   string  `json:"hr_setting"`
		SpeedSetting                string  `json:"speed_setting"`
		DistSetting                 string  `json:"dist_setting"`
		ActivityClass               int     `json:"activity_class"`
		PositionSetting             string  `json:"position_setting"`
		TemperatureSetting          string  `json:"temperature_setting"`
		HeightSetting               string  `json:"height_setting"`
	} `json:"user_profile"`
	Sport struct {
		Name     string `json:"name"`
		Sport    string `json:"sport"`
		SubSport string `json:"sub_sport"`
	} `json:"sport"`
	ZonesTargets []struct {
		FunctionalThresholdPower       float64 `json:"functional_threshold_power"`
		FunctionalThresholdPowerOffset float64 `json:"functional_threshold_power_offset"`
		FunctionalThresholdPowerScale  float64 `json:"functional_threshold_power_scale"`
		FunctionalThresholdPowerUnit   string  `json:"functional_threshold_power_unit"`
		MaxHeartRate                   float64 `json:"max_heart_rate"`
		MaxHeartRateOffset             float64 `json:"max_heart_rate_offset"`
		MaxHeartRateScale              float64 `json:"max_heart_rate_scale"`
		MaxHeartRateUnit               string  `json:"max_heart_rate_unit"`
		ThresholdHeartRate             float64 `json:"threshold_heart_rate"`
		ThresholdHeartRateOffset       float64 `json:"threshold_heart_rate_offset"`
		ThresholdHeartRateScale        float64 `json:"threshold_heart_rate_scale"`
		ThresholdHeartRateUnit         string  `json:"threshold_heart_rate_unit"`
		HrCalcType                     string  `json:"hr_calc_type"`
		PwrCalcType                    string  `json:"pwr_calc_type"`
	} `json:"zones_targets"`
	Records []struct {
		Timestamp               int     `json:"timestamp"`
		PositionLat             float64 `json:"position_lat"`
		PositionLong            float64 `json:"position_long"`
		Distance                float64 `json:"distance"`
		TimeFromCourse          float64 `json:"timeFromCourse"`
		CompressedSpeedDistance float64 `json:"compressedSpeedDistance"`
		HeartRate               int     `json:"heart_rate"`
		Altitude                float64 `json:"altitude"`
		Speed                   float64 `json:"speed"`
		Power                   float64 `json:"power"`
		Grade                   float64 `json:"grade"`
		Cadence                 int     `json:"cadence"`
		FractionalCadence       int     `json:"fractional_cadence"`
		Registance              float64 `json:"registance"`
		CycleLength             float64 `json:"cycleLength"`
		Temperature             float64 `json:"temperature"`
		AccumulatedPower        float64 `json:"accumulated_power"`
	} `json:"records"`
	Laps []struct {
		Timestamp                         float64   `json:"timestamp"`
		TimestampOffset                   float64   `json:"timestamp_offset"`
		TimestampScale                    float64   `json:"timestamp_scale"`
		TimestampUnit                     string    `json:"timestamp_unit"`
		StartTime                         float64   `json:"start_time"`
		StartTimeOffset                   float64   `json:"start_time_offset"`
		StartTimeScale                    float64   `json:"start_time_scale"`
		StartTimeUnit                     string    `json:"start_time_unit"`
		StartPositionLat                  float64   `json:"start_position_lat"`
		StartPositionLatOffset            float64   `json:"start_position_lat_offset"`
		StartPositionLatScale             float64   `json:"start_position_lat_scale"`
		StartPositionLatUnit              string    `json:"start_position_lat_unit"`
		StartPositionLong                 float64   `json:"start_position_long"`
		StartPositionLongOffset           float64   `json:"start_position_long_offset"`
		StartPositionLongScale            float64   `json:"start_position_long_scale"`
		StartPositionLongUnit             string    `json:"start_position_long_unit"`
		EndPositionLat                    float64   `json:"end_position_lat"`
		EndPositionLatOffset              float64   `json:"end_position_lat_offset"`
		EndPositionLatScale               float64   `json:"end_position_lat_scale"`
		EndPositionLatUnit                string    `json:"end_position_lat_unit"`
		EndPositionLong                   float64   `json:"end_position_long"`
		EndPositionLongOffset             float64   `json:"end_position_long_offset"`
		EndPositionLongScale              float64   `json:"end_position_long_scale"`
		EndPositionLongUnit               string    `json:"end_position_long_unit"`
		TotalElapsedTime                  float64   `json:"total_elapsed_time"`
		TotalElapsedTimeOffset            float64   `json:"total_elapsed_time_offset"`
		TotalElapsedTimeScale             float64   `json:"total_elapsed_time_scale"`
		TotalElapsedTimeUnit              string    `json:"total_elapsed_time_unit"`
		TotalTimerTime                    float64   `json:"total_timer_time"`
		TotalTimerTimeOffset              float64   `json:"total_timer_time_offset"`
		TotalTimerTimeScale               float64   `json:"total_timer_time_scale"`
		TotalTimerTimeUnit                string    `json:"total_timer_time_unit"`
		TotalDistance                     float64   `json:"total_distance"`
		TotalDistanceOffset               float64   `json:"total_distance_offset"`
		TotalDistanceScale                float64   `json:"total_distance_scale"`
		TotalDistanceUnit                 string    `json:"total_distance_unit"`
		TotalCycles                       float64   `json:"total_cycles"`
		TotalCyclesOffset                 float64   `json:"total_cycles_offset"`
		TotalCyclesScale                  float64   `json:"total_cycles_scale"`
		TotalCyclesUnit                   string    `json:"total_cycles_unit"`
		TotalWork                         float64   `json:"total_work"`
		TotalWorkOffset                   float64   `json:"total_work_offset"`
		TotalWorkScale                    float64   `json:"total_work_scale"`
		TotalWorkUnit                     string    `json:"total_work_unit"`
		TimeStanding                      float64   `json:"time_standing"`
		TimeStandingOffset                float64   `json:"time_standing_offset"`
		TimeStandingScale                 float64   `json:"time_standing_scale"`
		TimeStandingUnit                  string    `json:"time_standing_unit"`
		AvgLeftPowerPhase                 []float64 `json:"avg_left_power_phase"`
		AvgLeftPowerPhaseOffset           float64   `json:"avg_left_power_phase_offset"`
		AvgLeftPowerPhaseScale            float64   `json:"avg_left_power_phase_scale"`
		AvgLeftPowerPhaseUnit             string    `json:"avg_left_power_phase_unit"`
		AvgLeftPowerPhasePeak             []float64 `json:"avg_left_power_phase_peak"`
		AvgLeftPowerPhasePeakOffset       float64   `json:"avg_left_power_phase_peak_offset"`
		AvgLeftPowerPhasePeakScale        float64   `json:"avg_left_power_phase_peak_scale"`
		AvgLeftPowerPhasePeakUnit         string    `json:"avg_left_power_phase_peak_unit"`
		AvgRightPowerPhase                []float64 `json:"avg_right_power_phase"`
		AvgRightPowerPhaseOffset          float64   `json:"avg_right_power_phase_offset"`
		AvgRightPowerPhaseScale           float64   `json:"avg_right_power_phase_scale"`
		AvgRightPowerPhaseUnit            string    `json:"avg_right_power_phase_unit"`
		AvgRightPowerPhasePeak            []float64 `json:"avg_right_power_phase_peak"`
		AvgRightPowerPhasePeakOffset      float64   `json:"avg_right_power_phase_peak_offset"`
		AvgRightPowerPhasePeakScale       float64   `json:"avg_right_power_phase_peak_scale"`
		AvgRightPowerPhasePeakUnit        string    `json:"avg_right_power_phase_peak_unit"`
		AvgPowerPosition                  []float64 `json:"avg_power_position"`
		AvgPowerPositionOffset            float64   `json:"avg_power_position_offset"`
		AvgPowerPositionScale             float64   `json:"avg_power_position_scale"`
		AvgPowerPositionUnit              string    `json:"avg_power_position_unit"`
		MaxPowerPosition                  []float64 `json:"max_power_position"`
		MaxPowerPositionOffset            float64   `json:"max_power_position_offset"`
		MaxPowerPositionScale             float64   `json:"max_power_position_scale"`
		MaxPowerPositionUnit              string    `json:"max_power_position_unit"`
		MessageIndex                      float64   `json:"message_index"`
		TotalCalories                     float64   `json:"total_calories"`
		TotalCaloriesOffset               float64   `json:"total_calories_offset"`
		TotalCaloriesScale                float64   `json:"total_calories_scale"`
		TotalCaloriesUnit                 string    `json:"total_calories_unit"`
		TotalFatCalories                  float64   `json:"total_fat_calories"`
		TotalFatCaloriesOffset            float64   `json:"total_fat_calories_offset"`
		TotalFatCaloriesScale             float64   `json:"total_fat_calories_scale"`
		TotalFatCaloriesUnit              string    `json:"total_fat_calories_unit"`
		AvgSpeed                          float64   `json:"avg_speed"`
		AvgSpeedOffset                    float64   `json:"avg_speed_offset"`
		AvgSpeedScale                     float64   `json:"avg_speed_scale"`
		AvgSpeedUnit                      string    `json:"avg_speed_unit"`
		MaxSpeed                          float64   `json:"max_speed"`
		MaxSpeedOffset                    float64   `json:"max_speed_offset"`
		MaxSpeedScale                     float64   `json:"max_speed_scale"`
		MaxSpeedUnit                      string    `json:"max_speed_unit"`
		AvgPower                          float64   `json:"avg_power"`
		AvgPowerOffset                    float64   `json:"avg_power_offset"`
		AvgPowerScale                     float64   `json:"avg_power_scale"`
		AvgPowerUnit                      string    `json:"avg_power_unit"`
		TotalDescent                      float64   `json:"total_descent"`
		TotalDescentOffset                float64   `json:"total_descent_offset"`
		TotalDescentScale                 float64   `json:"total_descent_scale"`
		TotalDescentUnit                  string    `json:"total_descent_unit"`
		TotalAscent                       float64   `json:"total_ascent"`
		TotalAscentOffset                 float64   `json:"total_ascent_offset"`
		TotalAscentScale                  float64   `json:"total_ascent_scale"`
		TotalAscentUnit                   string    `json:"total_ascent_unit"`
		NumLengths                        float64   `json:"num_lengths"`
		NumLengthsOffset                  float64   `json:"num_lengths_offset"`
		NumLengthsScale                   float64   `json:"num_lengths_scale"`
		NumLengthsUnit                    string    `json:"num_lengths_unit"`
		MaxPower                          float64   `json:"max_power"`
		MaxPowerOffset                    float64   `json:"max_power_offset"`
		MaxPowerScale                     float64   `json:"max_power_scale"`
		MaxPowerUnit                      string    `json:"max_power_unit"`
		NormalizedPower                   float64   `json:"normalized_power"`
		NormalizedPowerOffset             float64   `json:"normalized_power_offset"`
		NormalizedPowerScale              float64   `json:"normalized_power_scale"`
		NormalizedPowerUnit               string    `json:"normalized_power_unit"`
		FirstLengthIndex                  float64   `json:"first_length_index"`
		FirstLengthIndexOffset            float64   `json:"first_length_index_offset"`
		FirstLengthIndexScale             float64   `json:"first_length_index_scale"`
		FirstLengthIndexUnit              string    `json:"first_length_index_unit"`
		Intensity                         float64   `json:"intensity"`
		IntensityOffset                   float64   `json:"intensity_offset"`
		IntensityScale                    float64   `json:"intensity_scale"`
		IntensityUnit                     string    `json:"intensity_unit"`
		LeftRightBalance                  float64   `json:"left_right_balance"`
		LeftRightBalanceOffset            float64   `json:"left_right_balance_offset"`
		LeftRightBalanceScale             float64   `json:"left_right_balance_scale"`
		LeftRightBalanceUnit              string    `json:"left_right_balance_unit"`
		AvgStrokeDistance                 float64   `json:"avg_stroke_distance"`
		AvgStrokeDistanceOffset           float64   `json:"avg_stroke_distance_offset"`
		AvgStrokeDistanceScale            float64   `json:"avg_stroke_distance_scale"`
		AvgStrokeDistanceUnit             string    `json:"avg_stroke_distance_unit"`
		MaxCadencePosition                []float64 `json:"max_cadence_position"`
		MaxCadencePositionOffset          float64   `json:"max_cadence_position_offset"`
		MaxCadencePositionScale           float64   `json:"max_cadence_position_scale"`
		MaxCadencePositionUnit            string    `json:"max_cadence_position_unit"`
		NumActiveLengths                  float64   `json:"num_active_lengths"`
		NumActiveLengthsOffset            float64   `json:"num_active_lengths_offset"`
		NumActiveLengthsScale             float64   `json:"num_active_lengths_scale"`
		NumActiveLengthsUnit              string    `json:"num_active_lengths_unit"`
		WktStepIndex                      float64   `json:"wkt_step_index"`
		WktStepIndexOffset                float64   `json:"wkt_step_index_offset"`
		WktStepIndexScale                 float64   `json:"wkt_step_index_scale"`
		WktStepIndexUnit                  string    `json:"wkt_step_index_unit"`
		AvgVerticalOscillation            float64   `json:"avg_vertical_oscillation"`
		AvgVerticalOscillationOffset      float64   `json:"avg_vertical_oscillation_offset"`
		AvgVerticalOscillationScale       float64   `json:"avg_vertical_oscillation_scale"`
		AvgVerticalOscillationUnit        string    `json:"avg_vertical_oscillation_unit"`
		AvgStanceTimePercent              float64   `json:"avg_stance_time_percent"`
		AvgStanceTimePercentOffset        float64   `json:"avg_stance_time_percent_offset"`
		AvgStanceTimePercentScale         float64   `json:"avg_stance_time_percent_scale"`
		AvgStanceTimePercentUnit          string    `json:"avg_stance_time_percent_unit"`
		AvgStanceTimeBalance              float64   `json:"avg_stance_time_balance"`
		AvgStanceTimeBalanceOffset        float64   `json:"avg_stance_time_balance_offset"`
		AvgStanceTimeBalanceScale         float64   `json:"avg_stance_time_balance_scale"`
		AvgStanceTimeBalanceUnit          string    `json:"avg_stance_time_balance_unit"`
		AvgStanceTime                     float64   `json:"avg_stance_time"`
		AvgStanceTimeOffset               float64   `json:"avg_stance_time_offset"`
		AvgStanceTimeScale                float64   `json:"avg_stance_time_scale"`
		AvgStanceTimeUnit                 string    `json:"avg_stance_time_unit"`
		StandCount                        float64   `json:"stand_count"`
		StandCountOffset                  float64   `json:"stand_count_offset"`
		StandCountScale                   float64   `json:"stand_count_scale"`
		StandCountUnit                    string    `json:"stand_count_unit"`
		AvgVerticalRatio                  float64   `json:"avg_vertical_ratio"`
		AvgVerticalRatioOffset            float64   `json:"avg_vertical_ratio_offset"`
		AvgVerticalRatioScale             float64   `json:"avg_vertical_ratio_scale"`
		AvgVerticalRatioUnit              string    `json:"avg_vertical_ratio_unit"`
		AvgStepLength                     float64   `json:"avg_step_length"`
		AvgStepLengthOffset               float64   `json:"avg_step_length_offset"`
		AvgStepLengthScale                float64   `json:"avg_step_length_scale"`
		AvgStepLengthUnit                 string    `json:"avg_step_length_unit"`
		Event                             string    `json:"event"`
		EventType                         string    `json:"event_type"`
		Sport                             string    `json:"sport"`
		SubSport                          string    `json:"sub_sport"`
		AvgHeartRate                      float64   `json:"avg_heart_rate"`
		AvgHeartRateOffset                float64   `json:"avg_heart_rate_offset"`
		AvgHeartRateScale                 float64   `json:"avg_heart_rate_scale"`
		AvgHeartRateUnit                  string    `json:"avg_heart_rate_unit"`
		MaxHeartRate                      float64   `json:"max_heart_rate"`
		MaxHeartRateOffset                float64   `json:"max_heart_rate_offset"`
		MaxHeartRateScale                 float64   `json:"max_heart_rate_scale"`
		MaxHeartRateUnit                  string    `json:"max_heart_rate_unit"`
		AvgCadence                        float64   `json:"avg_cadence"`
		AvgCadenceOffset                  float64   `json:"avg_cadence_offset"`
		AvgCadenceScale                   float64   `json:"avg_cadence_scale"`
		AvgCadenceUnit                    string    `json:"avg_cadence_unit"`
		MaxCadence                        float64   `json:"max_cadence"`
		MaxCadenceOffset                  float64   `json:"max_cadence_offset"`
		MaxCadenceScale                   float64   `json:"max_cadence_scale"`
		MaxCadenceUnit                    string    `json:"max_cadence_unit"`
		LapTrigger                        string    `json:"lap_trigger"`
		EventGroup                        float64   `json:"event_group"`
		EventGroupOffset                  float64   `json:"event_group_offset"`
		EventGroupScale                   float64   `json:"event_group_scale"`
		EventGroupUnit                    string    `json:"event_group_unit"`
		SwimStroke                        float64   `json:"swim_stroke"`
		SwimStrokeOffset                  float64   `json:"swim_stroke_offset"`
		SwimStrokeScale                   float64   `json:"swim_stroke_scale"`
		SwimStrokeUnit                    string    `json:"swim_stroke_unit"`
		AvgTemperature                    float64   `json:"avg_temperature"`
		AvgTemperatureOffset              float64   `json:"avg_temperature_offset"`
		AvgTemperatureScale               float64   `json:"avg_temperature_scale"`
		AvgTemperatureUnit                string    `json:"avg_temperature_unit"`
		MaxTemperature                    float64   `json:"max_temperature"`
		MaxTemperatureOffset              float64   `json:"max_temperature_offset"`
		MaxTemperatureScale               float64   `json:"max_temperature_scale"`
		MaxTemperatureUnit                string    `json:"max_temperature_unit"`
		AvgFractionalCadence              float64   `json:"avg_fractional_cadence"`
		AvgFractionalCadenceOffset        float64   `json:"avg_fractional_cadence_offset"`
		AvgFractionalCadenceScale         float64   `json:"avg_fractional_cadence_scale"`
		AvgFractionalCadenceUnit          string    `json:"avg_fractional_cadence_unit"`
		MaxFractionalCadence              float64   `json:"max_fractional_cadence"`
		MaxFractionalCadenceOffset        float64   `json:"max_fractional_cadence_offset"`
		MaxFractionalCadenceScale         float64   `json:"max_fractional_cadence_scale"`
		MaxFractionalCadenceUnit          string    `json:"max_fractional_cadence_unit"`
		TotalFractionalCycles             float64   `json:"total_fractional_cycles"`
		TotalFractionalCyclesOffset       float64   `json:"total_fractional_cycles_offset"`
		TotalFractionalCyclesScale        float64   `json:"total_fractional_cycles_scale"`
		TotalFractionalCyclesUnit         string    `json:"total_fractional_cycles_unit"`
		AvgRightTorqueEffectiveness       float64   `json:"avg_right_torque_effectiveness"`
		AvgRightTorqueEffectivenessOffset float64   `json:"avg_right_torque_effectiveness_offset"`
		AvgRightTorqueEffectivenessScale  float64   `json:"avg_right_torque_effectiveness_scale"`
		AvgRightTorqueEffectivenessUnit   string    `json:"avg_right_torque_effectiveness_unit"`
		AvgLeftTorqueEffectiveness        float64   `json:"avg_left_torque_effectiveness"`
		AvgLeftTorqueEffectivenessOffset  float64   `json:"avg_left_torque_effectiveness_offset"`
		AvgLeftTorqueEffectivenessScale   float64   `json:"avg_left_torque_effectiveness_scale"`
		AvgLeftTorqueEffectivenessUnit    string    `json:"avg_left_torque_effectiveness_unit"`
		AvgLeftPedalSmoothness            float64   `json:"avg_left_pedal_smoothness"`
		AvgLeftPedalSmoothnessOffset      float64   `json:"avg_left_pedal_smoothness_offset"`
		AvgLeftPedalSmoothnessScale       float64   `json:"avg_left_pedal_smoothness_scale"`
		AvgLeftPedalSmoothnessUnit        string    `json:"avg_left_pedal_smoothness_unit"`
		AvgRightPedalSmoothness           float64   `json:"avg_right_pedal_smoothness"`
		AvgRightPedalSmoothnessOffset     float64   `json:"avg_right_pedal_smoothness_offset"`
		AvgRightPedalSmoothnessScale      float64   `json:"avg_right_pedal_smoothness_scale"`
		AvgRightPedalSmoothnessUnit       string    `json:"avg_right_pedal_smoothness_unit"`
		AvgCombinedPedalSmoothness        float64   `json:"avg_combined_pedal_smoothness"`
		AvgCombinedPedalSmoothnessOffset  float64   `json:"avg_combined_pedal_smoothness_offset"`
		AvgCombinedPedalSmoothnessScale   float64   `json:"avg_combined_pedal_smoothness_scale"`
		AvgCombinedPedalSmoothnessUnit    string    `json:"avg_combined_pedal_smoothness_unit"`
		SportIndex                        float64   `json:"sport_index"`
		SportIndexOffset                  float64   `json:"sport_index_offset"`
		SportIndexScale                   float64   `json:"sport_index_scale"`
		SportIndexUnit                    string    `json:"sport_index_unit"`
		AvgLeftPco                        float64   `json:"avg_left_pco"`
		AvgLeftPcoOffset                  float64   `json:"avg_left_pco_offset"`
		AvgLeftPcoScale                   float64   `json:"avg_left_pco_scale"`
		AvgLeftPcoUnit                    string    `json:"avg_left_pco_unit"`
		AvgRightPco                       float64   `json:"avg_right_pco"`
		AvgRightPcoOffset                 float64   `json:"avg_right_pco_offset"`
		AvgRightPcoScale                  float64   `json:"avg_right_pco_scale"`
		AvgRightPcoUnit                   string    `json:"avg_right_pco_unit"`
		AvgCadencePosition                []float64 `json:"avg_cadence_position"`
		AvgCadencePositionOffset          float64   `json:"avg_cadence_position_offset"`
		AvgCadencePositionScale           float64   `json:"avg_cadence_position_scale"`
		AvgCadencePositionUnit            string    `json:"avg_cadence_position_unit"`
	} `json:"laps"`
	Session struct {
		Timestamp                         float64   `json:"timestamp"`
		TimestampOffset                   float64   `json:"timestamp_offset"`
		TimestampScale                    float64   `json:"timestamp_scale"`
		TimestampUnit                     string    `json:"timestamp_unit"`
		StartTime                         float64   `json:"start_time"`
		StartTimeOffset                   float64   `json:"start_time_offset"`
		StartTimeScale                    float64   `json:"start_time_scale"`
		StartTimeUnit                     string    `json:"start_time_unit"`
		StartPositionLat                  float64   `json:"start_position_lat"`
		StartPositionLatOffset            float64   `json:"start_position_lat_offset"`
		StartPositionLatScale             float64   `json:"start_position_lat_scale"`
		StartPositionLatUnit              string    `json:"start_position_lat_unit"`
		StartPositionLong                 float64   `json:"start_position_long"`
		StartPositionLongOffset           float64   `json:"start_position_long_offset"`
		StartPositionLongScale            float64   `json:"start_position_long_scale"`
		StartPositionLongUnit             string    `json:"start_position_long_unit"`
		TotalElapsedTime                  float64   `json:"total_elapsed_time"`
		TotalElapsedTimeOffset            float64   `json:"total_elapsed_time_offset"`
		TotalElapsedTimeScale             float64   `json:"total_elapsed_time_scale"`
		TotalElapsedTimeUnit              string    `json:"total_elapsed_time_unit"`
		TotalTimerTime                    float64   `json:"total_timer_time"`
		TotalTimerTimeOffset              float64   `json:"total_timer_time_offset"`
		TotalTimerTimeScale               float64   `json:"total_timer_time_scale"`
		TotalTimerTimeUnit                string    `json:"total_timer_time_unit"`
		TotalDistance                     float64   `json:"total_distance"`
		TotalDistanceOffset               float64   `json:"total_distance_offset"`
		TotalDistanceScale                float64   `json:"total_distance_scale"`
		TotalDistanceUnit                 string    `json:"total_distance_unit"`
		TotalCycles                       float64   `json:"total_cycles"`
		TotalCyclesOffset                 float64   `json:"total_cycles_offset"`
		TotalCyclesScale                  float64   `json:"total_cycles_scale"`
		TotalCyclesUnit                   string    `json:"total_cycles_unit"`
		NecLat                            float64   `json:"nec_lat"`
		NecLatOffset                      float64   `json:"nec_lat_offset"`
		NecLatScale                       float64   `json:"nec_lat_scale"`
		NecLatUnit                        string    `json:"nec_lat_unit"`
		NecLong                           float64   `json:"nec_long"`
		NecLongOffset                     float64   `json:"nec_long_offset"`
		NecLongScale                      float64   `json:"nec_long_scale"`
		NecLongUnit                       string    `json:"nec_long_unit"`
		SwcLat                            float64   `json:"swc_lat"`
		SwcLatOffset                      float64   `json:"swc_lat_offset"`
		SwcLatScale                       float64   `json:"swc_lat_scale"`
		SwcLatUnit                        string    `json:"swc_lat_unit"`
		SwcLong                           float64   `json:"swc_long"`
		SwcLongOffset                     float64   `json:"swc_long_offset"`
		SwcLongScale                      float64   `json:"swc_long_scale"`
		SwcLongUnit                       string    `json:"swc_long_unit"`
		AvgStrokeCount                    float64   `json:"avg_stroke_count"`
		AvgStrokeCountOffset              float64   `json:"avg_stroke_count_offset"`
		AvgStrokeCountScale               float64   `json:"avg_stroke_count_scale"`
		AvgStrokeCountUnit                string    `json:"avg_stroke_count_unit"`
		TotalWork                         float64   `json:"total_work"`
		TotalWorkOffset                   float64   `json:"total_work_offset"`
		TotalWorkScale                    float64   `json:"total_work_scale"`
		TotalWorkUnit                     string    `json:"total_work_unit"`
		TimeStanding                      float64   `json:"time_standing"`
		TimeStandingOffset                float64   `json:"time_standing_offset"`
		TimeStandingScale                 float64   `json:"time_standing_scale"`
		TimeStandingUnit                  string    `json:"time_standing_unit"`
		AvgLeftPowerPhase                 []float64 `json:"avg_left_power_phase"`
		AvgLeftPowerPhaseOffset           float64   `json:"avg_left_power_phase_offset"`
		AvgLeftPowerPhaseScale            float64   `json:"avg_left_power_phase_scale"`
		AvgLeftPowerPhaseUnit             string    `json:"avg_left_power_phase_unit"`
		AvgLeftPowerPhasePeak             []float64 `json:"avg_left_power_phase_peak"`
		AvgLeftPowerPhasePeakOffset       float64   `json:"avg_left_power_phase_peak_offset"`
		AvgLeftPowerPhasePeakScale        float64   `json:"avg_left_power_phase_peak_scale"`
		AvgLeftPowerPhasePeakUnit         string    `json:"avg_left_power_phase_peak_unit"`
		AvgRightPowerPhase                []float64 `json:"avg_right_power_phase"`
		AvgRightPowerPhaseOffset          float64   `json:"avg_right_power_phase_offset"`
		AvgRightPowerPhaseScale           float64   `json:"avg_right_power_phase_scale"`
		AvgRightPowerPhaseUnit            string    `json:"avg_right_power_phase_unit"`
		AvgRightPowerPhasePeak            []float64 `json:"avg_right_power_phase_peak"`
		AvgRightPowerPhasePeakOffset      float64   `json:"avg_right_power_phase_peak_offset"`
		AvgRightPowerPhasePeakScale       float64   `json:"avg_right_power_phase_peak_scale"`
		AvgRightPowerPhasePeakUnit        string    `json:"avg_right_power_phase_peak_unit"`
		AvgPowerPosition                  []float64 `json:"avg_power_position"`
		AvgPowerPositionOffset            float64   `json:"avg_power_position_offset"`
		AvgPowerPositionScale             float64   `json:"avg_power_position_scale"`
		AvgPowerPositionUnit              string    `json:"avg_power_position_unit"`
		MaxPowerPosition                  []float64 `json:"max_power_position"`
		MaxPowerPositionOffset            float64   `json:"max_power_position_offset"`
		MaxPowerPositionScale             float64   `json:"max_power_position_scale"`
		MaxPowerPositionUnit              string    `json:"max_power_position_unit"`
		MessageIndex                      float64   `json:"message_index"`
		TotalCalories                     float64   `json:"total_calories"`
		TotalCaloriesOffset               float64   `json:"total_calories_offset"`
		TotalCaloriesScale                float64   `json:"total_calories_scale"`
		TotalCaloriesUnit                 string    `json:"total_calories_unit"`
		AvgSpeed                          float64   `json:"avg_speed"`
		AvgSpeedOffset                    float64   `json:"avg_speed_offset"`
		AvgSpeedScale                     float64   `json:"avg_speed_scale"`
		AvgSpeedUnit                      string    `json:"avg_speed_unit"`
		MaxSpeed                          float64   `json:"max_speed"`
		MaxSpeedOffset                    float64   `json:"max_speed_offset"`
		MaxSpeedScale                     float64   `json:"max_speed_scale"`
		MaxSpeedUnit                      string    `json:"max_speed_unit"`
		AvgPower                          float64   `json:"avg_power"`
		AvgPowerOffset                    float64   `json:"avg_power_offset"`
		AvgPowerScale                     float64   `json:"avg_power_scale"`
		AvgPowerUnit                      string    `json:"avg_power_unit"`
		TotalDescent                      float64   `json:"total_descent"`
		TotalDescentOffset                float64   `json:"total_descent_offset"`
		TotalDescentScale                 float64   `json:"total_descent_scale"`
		TotalDescentUnit                  string    `json:"total_descent_unit"`
		TotalAscent                       float64   `json:"total_ascent"`
		TotalAscentOffset                 float64   `json:"total_ascent_offset"`
		TotalAscentScale                  float64   `json:"total_ascent_scale"`
		TotalAscentUnit                   string    `json:"total_ascent_unit"`
		MaxPower                          float64   `json:"max_power"`
		MaxPowerOffset                    float64   `json:"max_power_offset"`
		MaxPowerScale                     float64   `json:"max_power_scale"`
		MaxPowerUnit                      string    `json:"max_power_unit"`
		ThresholdPower                    float64   `json:"threshold_power"`
		ThresholdPowerOffset              float64   `json:"threshold_power_offset"`
		ThresholdPowerScale               float64   `json:"threshold_power_scale"`
		ThresholdPowerUnit                string    `json:"threshold_power_unit"`
		FirstLapIndex                     float64   `json:"first_lap_index"`
		FirstLapIndexOffset               float64   `json:"first_lap_index_offset"`
		FirstLapIndexScale                float64   `json:"first_lap_index_scale"`
		FirstLapIndexUnit                 string    `json:"first_lap_index_unit"`
		NumLaps                           float64   `json:"num_laps"`
		NumLapsOffset                     float64   `json:"num_laps_offset"`
		NumLapsScale                      float64   `json:"num_laps_scale"`
		NumLapsUnit                       string    `json:"num_laps_unit"`
		NormalizedPower                   float64   `json:"normalized_power"`
		NormalizedPowerOffset             float64   `json:"normalized_power_offset"`
		NormalizedPowerScale              float64   `json:"normalized_power_scale"`
		NormalizedPowerUnit               string    `json:"normalized_power_unit"`
		TrainingStressScore               float64   `json:"training_stress_score"`
		TrainingStressScoreOffset         float64   `json:"training_stress_score_offset"`
		TrainingStressScoreScale          float64   `json:"training_stress_score_scale"`
		TrainingStressScoreUnit           string    `json:"training_stress_score_unit"`
		IntensityFactor                   float64   `json:"intensity_factor"`
		IntensityFactorOffset             float64   `json:"intensity_factor_offset"`
		IntensityFactorScale              float64   `json:"intensity_factor_scale"`
		IntensityFactorUnit               string    `json:"intensity_factor_unit"`
		LeftRightBalance                  float64   `json:"left_right_balance"`
		LeftRightBalanceOffset            float64   `json:"left_right_balance_offset"`
		LeftRightBalanceScale             float64   `json:"left_right_balance_scale"`
		LeftRightBalanceUnit              string    `json:"left_right_balance_unit"`
		AvgStrokeDistance                 float64   `json:"avg_stroke_distance"`
		AvgStrokeDistanceOffset           float64   `json:"avg_stroke_distance_offset"`
		AvgStrokeDistanceScale            float64   `json:"avg_stroke_distance_scale"`
		AvgStrokeDistanceUnit             string    `json:"avg_stroke_distance_unit"`
		PoolLength                        float64   `json:"pool_length"`
		PoolLengthOffset                  float64   `json:"pool_length_offset"`
		PoolLengthScale                   float64   `json:"pool_length_scale"`
		PoolLengthUnit                    string    `json:"pool_length_unit"`
		MaxCadencePosition                []float64 `json:"max_cadence_position"`
		MaxCadencePositionOffset          float64   `json:"max_cadence_position_offset"`
		MaxCadencePositionScale           float64   `json:"max_cadence_position_scale"`
		MaxCadencePositionUnit            string    `json:"max_cadence_position_unit"`
		NumActiveLengths                  float64   `json:"num_active_lengths"`
		NumActiveLengthsOffset            float64   `json:"num_active_lengths_offset"`
		NumActiveLengthsScale             float64   `json:"num_active_lengths_scale"`
		NumActiveLengthsUnit              string    `json:"num_active_lengths_unit"`
		AvgVerticalOscillation            float64   `json:"avg_vertical_oscillation"`
		AvgVerticalOscillationOffset      float64   `json:"avg_vertical_oscillation_offset"`
		AvgVerticalOscillationScale       float64   `json:"avg_vertical_oscillation_scale"`
		AvgVerticalOscillationUnit        string    `json:"avg_vertical_oscillation_unit"`
		AvgStanceTimePercent              float64   `json:"avg_stance_time_percent"`
		AvgStanceTimePercentOffset        float64   `json:"avg_stance_time_percent_offset"`
		AvgStanceTimePercentScale         float64   `json:"avg_stance_time_percent_scale"`
		AvgStanceTimePercentUnit          string    `json:"avg_stance_time_percent_unit"`
		AvgStanceTimeBalance              float64   `json:"avg_stance_time_balance"`
		AvgStanceTimeBalanceOffset        float64   `json:"avg_stance_time_balance_offset"`
		AvgStanceTimeBalanceScale         float64   `json:"avg_stance_time_balance_scale"`
		AvgStanceTimeBalanceUnit          string    `json:"avg_stance_time_balance_unit"`
		AvgStanceTime                     float64   `json:"avg_stance_time"`
		AvgStanceTimeOffset               float64   `json:"avg_stance_time_offset"`
		AvgStanceTimeScale                float64   `json:"avg_stance_time_scale"`
		AvgStanceTimeUnit                 string    `json:"avg_stance_time_unit"`
		StandCount                        float64   `json:"stand_count"`
		StandCountOffset                  float64   `json:"stand_count_offset"`
		StandCountScale                   float64   `json:"stand_count_scale"`
		StandCountUnit                    string    `json:"stand_count_unit"`
		AvgVerticalRatio                  float64   `json:"avg_vertical_ratio"`
		AvgVerticalRatioOffset            float64   `json:"avg_vertical_ratio_offset"`
		AvgVerticalRatioScale             float64   `json:"avg_vertical_ratio_scale"`
		AvgVerticalRatioUnit              string    `json:"avg_vertical_ratio_unit"`
		AvgStepLength                     float64   `json:"avg_step_length"`
		AvgStepLengthOffset               float64   `json:"avg_step_length_offset"`
		AvgStepLengthScale                float64   `json:"avg_step_length_scale"`
		AvgStepLengthUnit                 string    `json:"avg_step_length_unit"`
		Event                             string    `json:"event"`
		EventType                         string    `json:"event_type"`
		Sport                             string    `json:"sport"`
		SubSport                          string    `json:"sub_sport"`
		AvgHeartRate                      float64   `json:"avg_heart_rate"`
		AvgHeartRateOffset                float64   `json:"avg_heart_rate_offset"`
		AvgHeartRateScale                 float64   `json:"avg_heart_rate_scale"`
		AvgHeartRateUnit                  string    `json:"avg_heart_rate_unit"`
		MaxHeartRate                      float64   `json:"max_heart_rate"`
		MaxHeartRateOffset                float64   `json:"max_heart_rate_offset"`
		MaxHeartRateScale                 float64   `json:"max_heart_rate_scale"`
		MaxHeartRateUnit                  string    `json:"max_heart_rate_unit"`
		AvgCadence                        float64   `json:"avg_cadence"`
		AvgCadenceOffset                  float64   `json:"avg_cadence_offset"`
		AvgCadenceScale                   float64   `json:"avg_cadence_scale"`
		AvgCadenceUnit                    string    `json:"avg_cadence_unit"`
		MaxCadence                        float64   `json:"max_cadence"`
		MaxCadenceOffset                  float64   `json:"max_cadence_offset"`
		MaxCadenceScale                   float64   `json:"max_cadence_scale"`
		MaxCadenceUnit                    string    `json:"max_cadence_unit"`
		TotalTrainingEffect               float64   `json:"total_training_effect"`
		TotalTrainingEffectOffset         float64   `json:"total_training_effect_offset"`
		TotalTrainingEffectScale          float64   `json:"total_training_effect_scale"`
		TotalTrainingEffectUnit           string    `json:"total_training_effect_unit"`
		EventGroup                        float64   `json:"event_group"`
		EventGroupOffset                  float64   `json:"event_group_offset"`
		EventGroupScale                   float64   `json:"event_group_scale"`
		EventGroupUnit                    string    `json:"event_group_unit"`
		Trigger                           string    `json:"trigger"`
		SwimStroke                        float64   `json:"swim_stroke"`
		SwimStrokeOffset                  float64   `json:"swim_stroke_offset"`
		SwimStrokeScale                   float64   `json:"swim_stroke_scale"`
		SwimStrokeUnit                    string    `json:"swim_stroke_unit"`
		AvgTemperature                    float64   `json:"avg_temperature"`
		AvgTemperatureOffset              float64   `json:"avg_temperature_offset"`
		AvgTemperatureScale               float64   `json:"avg_temperature_scale"`
		AvgTemperatureUnit                string    `json:"avg_temperature_unit"`
		MaxTemperature                    float64   `json:"max_temperature"`
		MaxTemperatureOffset              float64   `json:"max_temperature_offset"`
		MaxTemperatureScale               float64   `json:"max_temperature_scale"`
		MaxTemperatureUnit                string    `json:"max_temperature_unit"`
		AvgFractionalCadence              float64   `json:"avg_fractional_cadence"`
		AvgFractionalCadenceOffset        float64   `json:"avg_fractional_cadence_offset"`
		AvgFractionalCadenceScale         float64   `json:"avg_fractional_cadence_scale"`
		AvgFractionalCadenceUnit          string    `json:"avg_fractional_cadence_unit"`
		MaxFractionalCadence              float64   `json:"max_fractional_cadence"`
		MaxFractionalCadenceOffset        float64   `json:"max_fractional_cadence_offset"`
		MaxFractionalCadenceScale         float64   `json:"max_fractional_cadence_scale"`
		MaxFractionalCadenceUnit          string    `json:"max_fractional_cadence_unit"`
		TotalFractionalCycles             float64   `json:"total_fractional_cycles"`
		TotalFractionalCyclesOffset       float64   `json:"total_fractional_cycles_offset"`
		TotalFractionalCyclesScale        float64   `json:"total_fractional_cycles_scale"`
		TotalFractionalCyclesUnit         string    `json:"total_fractional_cycles_unit"`
		AvgRightTorqueEffectiveness       float64   `json:"avg_right_torque_effectiveness"`
		AvgRightTorqueEffectivenessOffset float64   `json:"avg_right_torque_effectiveness_offset"`
		AvgRightTorqueEffectivenessScale  float64   `json:"avg_right_torque_effectiveness_scale"`
		AvgRightTorqueEffectivenessUnit   string    `json:"avg_right_torque_effectiveness_unit"`
		AvgLeftPedalSmoothness            float64   `json:"avg_left_pedal_smoothness"`
		AvgLeftPedalSmoothnessOffset      float64   `json:"avg_left_pedal_smoothness_offset"`
		AvgLeftPedalSmoothnessScale       float64   `json:"avg_left_pedal_smoothness_scale"`
		AvgLeftPedalSmoothnessUnit        string    `json:"avg_left_pedal_smoothness_unit"`
		AvgLeftTorqueEffectiveness        float64   `json:"avg_left_torque_effectiveness"`
		AvgLeftTorqueEffectivenessOffset  float64   `json:"avg_left_torque_effectiveness_offset"`
		AvgLeftTorqueEffectivenessScale   float64   `json:"avg_left_torque_effectiveness_scale"`
		AvgLeftTorqueEffectivenessUnit    string    `json:"avg_left_torque_effectiveness_unit"`
		AvgRightPedalSmoothness           float64   `json:"avg_right_pedal_smoothness"`
		AvgRightPedalSmoothnessOffset     float64   `json:"avg_right_pedal_smoothness_offset"`
		AvgRightPedalSmoothnessScale      float64   `json:"avg_right_pedal_smoothness_scale"`
		AvgRightPedalSmoothnessUnit       string    `json:"avg_right_pedal_smoothness_unit"`
		AvgCombinedPedalSmoothness        float64   `json:"avg_combined_pedal_smoothness"`
		AvgCombinedPedalSmoothnessOffset  float64   `json:"avg_combined_pedal_smoothness_offset"`
		AvgCombinedPedalSmoothnessScale   float64   `json:"avg_combined_pedal_smoothness_scale"`
		AvgCombinedPedalSmoothnessUnit    string    `json:"avg_combined_pedal_smoothness_unit"`
		SportIndex                        float64   `json:"sport_index"`
		SportIndexOffset                  float64   `json:"sport_index_offset"`
		SportIndexScale                   float64   `json:"sport_index_scale"`
		SportIndexUnit                    string    `json:"sport_index_unit"`
		AvgLeftPco                        float64   `json:"avg_left_pco"`
		AvgLeftPcoOffset                  float64   `json:"avg_left_pco_offset"`
		AvgLeftPcoScale                   float64   `json:"avg_left_pco_scale"`
		AvgLeftPcoUnit                    string    `json:"avg_left_pco_unit"`
		AvgRightPco                       float64   `json:"avg_right_pco"`
		AvgRightPcoOffset                 float64   `json:"avg_right_pco_offset"`
		AvgRightPcoScale                  float64   `json:"avg_right_pco_scale"`
		AvgRightPcoUnit                   string    `json:"avg_right_pco_unit"`
		AvgCadencePosition                []float64 `json:"avg_cadence_position"`
		AvgCadencePositionOffset          float64   `json:"avg_cadence_position_offset"`
		AvgCadencePositionScale           float64   `json:"avg_cadence_position_scale"`
		AvgCadencePositionUnit            string    `json:"avg_cadence_position_unit"`
	} `json:"session"`
	Activity struct {
		Timestamp            float64 `json:"timestamp"`
		TimestampOffset      float64 `json:"timestamp_offset"`
		TimestampScale       float64 `json:"timestamp_scale"`
		TimestampUnit        string  `json:"timestamp_unit"`
		TotalTimerTime       float64 `json:"total_timer_time"`
		TotalTimerTimeOffset float64 `json:"total_timer_time_offset"`
		TotalTimerTimeScale  float64 `json:"total_timer_time_scale"`
		TotalTimerTimeUnit   string  `json:"total_timer_time_unit"`
		LocalDateTime        float64 `json:"local_date_time"`
		LocalDateTimeOffset  float64 `json:"local_date_time_offset"`
		LocalDateTimeScale   float64 `json:"local_date_time_scale"`
		LocalDateTimeUnit    string  `json:"local_date_time_unit"`
		NumSessions          float64 `json:"num_sessions"`
		NumSessionsOffset    float64 `json:"num_sessions_offset"`
		NumSessionsScale     float64 `json:"num_sessions_scale"`
		NumSessionsUnit      string  `json:"num_sessions_unit"`
		Type                 string  `json:"type"`
		Event                string  `json:"event"`
		EventType            string  `json:"event_type"`
		EventGroup           float64 `json:"event_group"`
	} `json:"activity"`
}
